# created by @jcoreio/toolchain-circle

version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0
jobs:
  build:
    docker:
      - image: cimg/node:20.10.0

    steps:
      - checkout
      - run:
          name: Setup NPM Token
          command: |
            npm config set \
              "//registry.npmjs.org/:_authToken=$NPM_TOKEN" \
              "registry=https://registry.npmjs.org/"
      - run:
          name: Corepack enable
          command: sudo corepack enable
      - run:
          name: Install Dependencies
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Prepublish
          command: |
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || (pnpm run -r --if-present tc prepublish && cd packages/create-clarity-plugin && pnpm run tc test)
      - codecov/upload
      - run:
          name: Release
          command: |
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm -r --workspace-concurrency=1 run --if-present -- tc release

workflows:
  build:
    jobs:
      - build:
          context:
            - npm-release
            - github-release
